-- SQL script to create A_NOTE and A_MONTHLY_SUMMARY tables
-- Run this on your SQLite database if migrations don't work

-- Create A_NOTE table
CREATE TABLE IF NOT EXISTS "A_NOTE" (
    "NOTEID" INTEGER NOT NULL CONSTRAINT "PK_A_NOTE" PRIMARY KEY AUTOINCREMENT,
    "USERID" INTEGER NOT NULL,
    "COURSEID" INTEGER NOT NULL,
    "NOTETITLE" TEXT NOT NULL,
    "NOTECONTENT" TEXT NOT NULL,
    "CREATIONDATE" TEXT NOT NULL,
    "MODIFICATIONDATE" TEXT NOT NULL,
    CONSTRAINT "FK_A_NOTE_T_USER_USERID" FOREIGN KEY ("USERID") REFERENCES "T_USER" ("USERID") ON DELETE CASCADE,
    CONSTRAINT "FK_A_NOTE_A_COURSE_COURSEID" FOREIGN KEY ("COURSEID") REFERENCES "A_COURSE" ("COURSEID") ON DELETE CASCADE
);

-- Create A_MONTHLY_SUMMARY table
CREATE TABLE IF NOT EXISTS "A_MONTHLY_SUMMARY" (
    "SUMMARYID" INTEGER NOT NULL CONSTRAINT "PK_A_MONTHLY_SUMMARY" PRIMARY KEY AUTOINCREMENT,
    "USERID" INTEGER NOT NULL,
    "YEAR" INTEGER NOT NULL,
    "MONTH" INTEGER NOT NULL,
    "SUMMARY" TEXT NOT NULL,
    "WHATLEARNED" TEXT NOT NULL,
    "WHATPRESENTED" TEXT NOT NULL,
    "CREATIONDATE" TEXT NOT NULL,
    "MODIFICATIONDATE" TEXT NOT NULL,
    CONSTRAINT "FK_A_MONTHLY_SUMMARY_T_USER_USERID" FOREIGN KEY ("USERID") REFERENCES "T_USER" ("USERID") ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "IX_A_NOTE_USERID_COURSEID" ON "A_NOTE" ("USERID", "COURSEID");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_A_MONTHLY_SUMMARY_USERID_YEAR_MONTH" ON "A_MONTHLY_SUMMARY" ("USERID", "YEAR", "MONTH");

-- Insert migration record into __EFMigrationsHistory
INSERT OR IGNORE INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250108000000_AddNotesAndMonthlySummaries', '9.0.10');

